### ISSUE TITLE
Inconsistent order of dependencies in return function parameters

### ISSUE THREAD

**Issue by khanhduong95** [elliotchance/dingo#19]
I have 4 services called Dep1, Dep2, Dep3 & Dep4 where Dep4 has Dep1, Dep2 & Dep3 as dependencies

```yml
services:
    Dep1:
      interface: app.Dep1
      scope: prototype
      returns: app.NewDefaultDep1()

    Dep2:
      interface: app.Dep2
      scope: prototype
      returns: app.NewDefaultDep2()

    Dep3:
      interface: app.Dep3
      scope: prototype
      returns: app.NewDefaultDep3()

    Dep4:
      interface: app.Dep4
      scope: prototype
      returns: app.NewDefaultDep4(@{Dep1}, @{Dep2}, @{Dep3})
```

Here is the first generated dingo.go (the order of parameters in Dep4's function in NewContainer() is different from the order in other places)

```go
// Code generated by dingo; DO NOT EDIT
package main

import app "app"

type Container struct {
	Dep1	func() app.Dep1
	Dep2	func() app.Dep2
	Dep3	func() app.Dep3
	Dep4	func(Dep1 app.Dep1, Dep2 app.Dep2, Dep3 app.Dep3) app.Dep4
}

var DefaultContainer = NewContainer()

func NewContainer() *Container {
	return &Container{Dep1: func() app.Dep1 {
		service := app.NewDefaultDep1()
		return service
	}, Dep2: func() app.Dep2 {
		service := app.NewDefaultDep2()
		return service
	}, Dep3: func() app.Dep3 {
		service := app.NewDefaultDep3()
		return service
	}, Dep4: func(Dep3 app.Dep3, Dep1 app.Dep1, Dep2 app.Dep2) app.Dep4 {
		service := app.NewDefaultDep4(Dep1, Dep2, Dep3)
		return service
	}}
}
func (container *Container) GetDep1() app.Dep1 {
	return container.Dep1()
}
func (container *Container) GetDep2() app.Dep2 {
	return container.Dep2()
}
func (container *Container) GetDep3() app.Dep3 {
	return container.Dep3()
}
func (container *Container) GetDep4() app.Dep4 {
	return container.Dep4(container.GetDep1(), container.GetDep2(), container.GetDep3())
}
```

Here is the second generated dingo.go (the order is the same in all places)

```go
// Code generated by dingo; DO NOT EDIT
package main

import app "app"

type Container struct {
	Dep1	func() app.Dep1
	Dep2	func() app.Dep2
	Dep3	func() app.Dep3
	Dep4	func(Dep1 app.Dep1, Dep2 app.Dep2, Dep3 app.Dep3) app.Dep4
}

var DefaultContainer = NewContainer()

func NewContainer() *Container {
	return &Container{Dep1: func() app.Dep1 {
		service := app.NewDefaultDep1()
		return service
	}, Dep2: func() app.Dep2 {
		service := app.NewDefaultDep2()
		return service
	}, Dep3: func() app.Dep3 {
		service := app.NewDefaultDep3()
		return service
	}, Dep4: func(Dep1 app.Dep1, Dep2 app.Dep2, Dep3 app.Dep3) app.Dep4 {
		service := app.NewDefaultDep4(Dep1, Dep2, Dep3)
		return service
	}}
}
func (container *Container) GetDep1() app.Dep1 {
	return container.Dep1()
}
func (container *Container) GetDep2() app.Dep2 {
	return container.Dep2()
}
func (container *Container) GetDep3() app.Dep3 {
	return container.Dep3()
}
func (container *Container) GetDep4() app.Dep4 {
	return container.Dep4(container.GetDep1(), container.GetDep2(), container.GetDep3())
}
```
