### ISSUE TITLE
Allow arguments for prototypes

### ISSUE THREAD

**Issue by elliotchance** [elliotchance/dingo#5]
This is extremely useful when using a factory pattern without needing an extra factory or extra step, like:

```yml
services:
  Emailer:
    type: *SendEmail
    scope: prototype
    arguments:
      - from string
    properties:
      From: from # Since we can use any Go expression here
```

Now it can be reused with custom initialization:

```go
emailer := DefaultContainer.GetEmailer("bob@smith.com")
```
